.TH "calculator" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
calculator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcalculate\fP (std::string input)"
.br
.RI "Takes an input string and puts it through the \fBcalculator::calculate\fP function\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int calculator::calculate (std::string input)"

.PP
Takes an input string and puts it through the \fBcalculator::calculate\fP function\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput\fP The string put in from the prompt in main\&.cpp 
.RE
.PP
\fBReturns\fP
.RS 4
result of calculation 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
