.TH "doctest::AssertData" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::AssertData
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdoctest::detail::ResultBuilder\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStringContains\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssertData\fP (assertType::Enum at, const char *file, int line, const char *expr, const char *exception_type, const \fBStringContains\fP &exception_string)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBTestCaseData\fP * \fBm_test_case\fP"
.br
.ti -1c
.RI "assertType::Enum \fBm_at\fP"
.br
.ti -1c
.RI "const char * \fBm_file\fP"
.br
.ti -1c
.RI "int \fBm_line\fP"
.br
.ti -1c
.RI "const char * \fBm_expr\fP"
.br
.ti -1c
.RI "bool \fBm_failed\fP"
.br
.ti -1c
.RI "bool \fBm_threw\fP"
.br
.ti -1c
.RI "\fBString\fP \fBm_exception\fP"
.br
.ti -1c
.RI "\fBString\fP \fBm_decomp\fP"
.br
.ti -1c
.RI "bool \fBm_threw_as\fP"
.br
.ti -1c
.RI "const char * \fBm_exception_type\fP"
.br
.ti -1c
.RI "class DOCTEST_INTERFACE \fBdoctest::AssertData::StringContains\fP \fBm_exception_string\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
