.TH "doctest::detail::RelationalComparator< int, L, R >" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::RelationalComparator< int, L, R >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const DOCTEST_REF_WRAP(L), const DOCTEST_REF_WRAP(R)) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
