.TH "doctest::detail::has_insertion_operator< T, decltype(operator<<(declval< std::ostream & >(), declval< const T & >()), void())>" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::has_insertion_operator< T, decltype(operator<<(declval< std::ostream & >(), declval< const T & >()), void())>
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdoctest::detail::types::true_type\fP\&.
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBdoctest::detail::types::true_type\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP DOCTEST_CONSTEXPR \fBbool\fP \fBvalue\fP = \fBtrue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
