.TH "doctest::detail::types::is_enum< T >" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::types::is_enum< T >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP DOCTEST_CONSTEXPR \fBbool\fP \fBvalue\fP = \fB__is_enum\fP(\fBT\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
