.TH "doctest::TestRunStats" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::TestRunStats
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnumTestCases\fP"
.br
.ti -1c
.RI "unsigned \fBnumTestCasesPassingFilters\fP"
.br
.ti -1c
.RI "unsigned \fBnumTestSuitesPassingFilters\fP"
.br
.ti -1c
.RI "unsigned \fBnumTestCasesFailed\fP"
.br
.ti -1c
.RI "int \fBnumAsserts\fP"
.br
.ti -1c
.RI "int \fBnumAssertsFailed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
