.TH "doctest::detail::types::is_rvalue_reference< T >" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::types::is_rvalue_reference< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdoctest::detail::types::false_type\fP\&.
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBdoctest::detail::types::false_type\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP DOCTEST_CONSTEXPR \fBbool\fP \fBvalue\fP = \fBfalse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
