.TH "doctest::detail::should_stringify_as_underlying_type< T >" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::should_stringify_as_underlying_type< T >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static DOCTEST_CONSTEXPR bool \fBvalue\fP = \fBdetail::types::is_enum\fP<T>::value && !\fBdoctest::detail::has_insertion_operator\fP<T>::value"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
