.TH "doctest::MessageData" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::MessageData
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdoctest::detail::MessageBuilder\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fBm_string\fP"
.br
.ti -1c
.RI "const char * \fBm_file\fP"
.br
.ti -1c
.RI "int \fBm_line\fP"
.br
.ti -1c
.RI "assertType::Enum \fBm_severity\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
