.TH "doctest::detail::ExceptionTranslator< T >" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::ExceptionTranslator< T > \- OCLINT destructor of virtual class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <doctest\&.h>\fP
.PP
Inherits \fBdoctest::detail::IExceptionTranslator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExceptionTranslator\fP (\fBString\fP(*translateFunction)(T))"
.br
.ti -1c
.RI "bool \fBtranslate\fP (\fBString\fP &res) const override"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class doctest::detail::ExceptionTranslator< T >"OCLINT destructor of virtual class\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > bool \fBdoctest::detail::ExceptionTranslator\fP< T >::translate (\fBString\fP & res) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBdoctest::detail::IExceptionTranslator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
