.TH "doctest::detail::types::remove_reference< T >" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::types::remove_reference< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBtype\fP = \fBT\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
