.TH "doctest::AssertData::StringContains" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::AssertData::StringContains
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStringContains\fP (const \fBString\fP &str)"
.br
.ti -1c
.RI "\fBStringContains\fP (\fBContains\fP cntn)"
.br
.ti -1c
.RI "bool \fBcheck\fP (const \fBString\fP &str)"
.br
.ti -1c
.RI "\fBoperator const String &\fP () const"
.br
.ti -1c
.RI "const char * \fBc_str\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
