.TH "doctest::detail::StringMakerBase< true >" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::StringMakerBase< true >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > static \fBString\fP \fBconvert\fP (const DOCTEST_REF_WRAP(T) in)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
