.TH "doctest::QueryData" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::QueryData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBTestRunStats\fP * \fBrun_stats\fP = nullptr"
.br
.ti -1c
.RI "const \fBTestCaseData\fP ** \fBdata\fP = nullptr"
.br
.ti -1c
.RI "unsigned \fBnum_data\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
