.TH "doctest::TestCaseData" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::TestCaseData
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdoctest::detail::TestCase\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fBm_file\fP"
.br
.ti -1c
.RI "unsigned \fBm_line\fP"
.br
.ti -1c
.RI "const char * \fBm_name\fP"
.br
.ti -1c
.RI "const char * \fBm_test_suite\fP"
.br
.ti -1c
.RI "const char * \fBm_description\fP"
.br
.ti -1c
.RI "bool \fBm_skip\fP"
.br
.ti -1c
.RI "bool \fBm_no_breaks\fP"
.br
.ti -1c
.RI "bool \fBm_no_output\fP"
.br
.ti -1c
.RI "bool \fBm_may_fail\fP"
.br
.ti -1c
.RI "bool \fBm_should_fail\fP"
.br
.ti -1c
.RI "int \fBm_expected_failures\fP"
.br
.ti -1c
.RI "double \fBm_timeout\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
