.TH "doctest::detail::types::underlying_type< T >" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::types::underlying_type< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBusing\fP \fBtype\fP = \fB__underlying_type\fP(\fBT\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
