.TH "doctest::CurrentTestCaseStats" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::CurrentTestCaseStats
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnumAssertsCurrentTest\fP"
.br
.ti -1c
.RI "int \fBnumAssertsFailedCurrentTest\fP"
.br
.ti -1c
.RI "double \fBseconds\fP"
.br
.ti -1c
.RI "int \fBfailure_flags\fP"
.br
.ti -1c
.RI "bool \fBtestCaseSuccess\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
