.TH "doctest::IsNaN< F >" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::IsNaN< F >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsNaN\fP (F f, bool flip=false)"
.br
.ti -1c
.RI "\fBIsNaN\fP< F > \fBoperator!\fP () const"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "F \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBflipped\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
