.TH "doctest::detail::TestSuite" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::TestSuite
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestSuite\fP & \fBoperator*\fP (const char *in)"
.br
.ti -1c
.RI "template<typename T > \fBTestSuite\fP & \fBoperator*\fP (const T &in)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBm_test_suite\fP = nullptr"
.br
.ti -1c
.RI "const char * \fBm_description\fP = nullptr"
.br
.ti -1c
.RI "bool \fBm_skip\fP = false"
.br
.ti -1c
.RI "bool \fBm_no_breaks\fP = false"
.br
.ti -1c
.RI "bool \fBm_no_output\fP = false"
.br
.ti -1c
.RI "bool \fBm_may_fail\fP = false"
.br
.ti -1c
.RI "bool \fBm_should_fail\fP = false"
.br
.ti -1c
.RI "int \fBm_expected_failures\fP = 0"
.br
.ti -1c
.RI "double \fBm_timeout\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
