.TH "doctest::detail::types::true_type" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::types::true_type
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdoctest::detail::has_insertion_operator< T, decltype(operator<<(declval< std::ostream & >(), declval< const T & >()), void())>\fP, \fBdoctest::detail::types::is_array< T[SIZE]>\fP, \fBdoctest::detail::types::is_pointer< T * >\fP, and \fBdoctest::detail::types::is_rvalue_reference< T && >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP DOCTEST_CONSTEXPR \fBbool\fP \fBvalue\fP = \fBtrue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
