.TH "md_math_2readme" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_math_2readme \- Math program 
.PP
 This program takes 2 numbers together by incrementing or decrementing by 1\&.
.br
 Every operation on top of a base operation (addition/subtraction) calls the base function to accomplish their tasks\&.
.SH "Currently supported operations:"
.PP
+: Addition
.br
 -: Subtraction
.br
 *: Multiplication
.br
 ^: Exponentation
.br
 t: Tetration (labeled as t because ↑ is not part of default Windows keyboard layouts or non-Unicode character sets and as such you can not use ↑↑)
.PP
In progress:
.PP
/: Division (bug: negative numbers always result in -1 due to it being the return value)
.SH "Build process"
.PP
.SS "Cloning the repository"
Type \fCgit clone https://github.com/ttaute/math\fP in your shell or click on 'Code', then on one of the options in here\&.
.SS "Building the program"
The main building environment used here is Visual Studio 2022\&. It will give you the least amount of pain\&.
.br
 Simply open up the project and press Ctrl-Shift-B\&. The output should be under the target folder (by default \\x64\\Debug)\&.
.br
.SS "Building the code documentation"
This program uses Doxygen to generate the code documentation\&. To build it yourself, type the following into your shell: \fCdoxygen Doxyfile\fP
.PP
Alternatively, open the file into the Doxygen wizard and pick your working and output directories\&.
.PP
It will generate HTML documentation and manpages\&.
.SH "Badges with barely any value for anything but development"
.PP
.SH "License"
.PP
This program is licensed under the MIT License\&.
.PP
A copy of it can be found under LICENSE\&.
.SH "Credits"
.PP
This program uses \fCdoctest\fP to build unit tests\&. 
