.TH "operation" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
operation
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBadd_operation\fP, \fBdiv_operation\fP, \fBmul_operation\fP, \fBpow_operation\fP, \fBsub_operation\fP, and \fBtet_operation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBcalculate\fP (int a, int b) const =0"
.br
.RI "Placeholder definition for the operations in the headers\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int operation::calculate (int a, int b) const\fC [pure virtual]\fP"

.PP
Placeholder definition for the operations in the headers\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP First number 
.br
\fIb\fP Second number 
.RE
.PP
\fBReturns\fP
.RS 4
The appropriate operation\&. 
.RE
.PP

.PP
Implemented in \fBadd_operation\fP, \fBdiv_operation\fP, \fBmul_operation\fP, \fBpow_operation\fP, \fBsub_operation\fP, and \fBtet_operation\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
