.TH "doctest::detail::IExceptionTranslator" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::IExceptionTranslator
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdoctest::detail::ExceptionTranslator< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBtranslate\fP (\fBString\fP &) const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
