.TH "doctest::detail::Subcase" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::Subcase
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubcase\fP (const \fBString\fP &name, const char *file, int line)"
.br
.ti -1c
.RI "\fBSubcase\fP (const \fBSubcase\fP &)=delete"
.br
.ti -1c
.RI "\fBSubcase\fP (\fBSubcase\fP &&)=delete"
.br
.ti -1c
.RI "\fBSubcase\fP & \fBoperator=\fP (const \fBSubcase\fP &)=delete"
.br
.ti -1c
.RI "\fBSubcase\fP & \fBoperator=\fP (\fBSubcase\fP &&)=delete"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSubcaseSignature\fP \fBm_signature\fP"
.br
.ti -1c
.RI "bool \fBm_entered\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
