.TH "doctest::detail::types::false_type" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::detail::types::false_type
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdoctest::detail::deferred_false< T >\fP, \fBdoctest::detail::has_insertion_operator< T, typename >\fP, \fBdoctest::detail::types::is_array< T >\fP, \fBdoctest::detail::types::is_pointer< T >\fP, and \fBdoctest::detail::types::is_rvalue_reference< T >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP DOCTEST_CONSTEXPR \fBbool\fP \fBvalue\fP = \fBfalse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
