.TH "doctest::StringMaker< T >" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::StringMaker< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdoctest::detail::StringMakerBase< detail::has_insertion_operator< T >::value||detail::types::is_pointer< T >::value||detail::types::is_array< T >::value >\fP\&.
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBdoctest::detail::StringMakerBase< detail::has_insertion_operator< T >::value||detail::types::is_pointer< T >::value||detail::types::is_array< T >::value >\fP
.in +1c
.ti -1c
.RI "static \fBString\fP \fBconvert\fP (const DOCTEST_REF_WRAP(T))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
