.TH "doctest::SubcaseSignature" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::SubcaseSignature
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBSubcaseSignature\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBSubcaseSignature\fP &other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fBm_name\fP"
.br
.ti -1c
.RI "const char * \fBm_file\fP"
.br
.ti -1c
.RI "int \fBm_line\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
