.TH "doctest::ContextOptions" 3 "Version latest" "math" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doctest::ContextOptions \- OCLINT too many fields\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <doctest\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd::ostream\fP * \fBcout\fP = nullptr"
.br
.ti -1c
.RI "\fBString\fP \fBbinary_name\fP"
.br
.ti -1c
.RI "const \fBdetail::TestCase\fP * \fBcurrentTest\fP = nullptr"
.br
.ti -1c
.RI "\fBString\fP \fBout\fP"
.br
.ti -1c
.RI "\fBString\fP \fBorder_by\fP"
.br
.ti -1c
.RI "unsigned \fBrand_seed\fP"
.br
.ti -1c
.RI "unsigned \fBfirst\fP"
.br
.ti -1c
.RI "unsigned \fBlast\fP"
.br
.ti -1c
.RI "int \fBabort_after\fP"
.br
.ti -1c
.RI "int \fBsubcase_filter_levels\fP"
.br
.ti -1c
.RI "bool \fBsuccess\fP"
.br
.ti -1c
.RI "bool \fBcase_sensitive\fP"
.br
.ti -1c
.RI "bool \fBexit\fP"
.br
.ti -1c
.RI "bool \fBduration\fP"
.br
.ti -1c
.RI "bool \fBminimal\fP"
.br
.ti -1c
.RI "bool \fBquiet\fP"
.br
.ti -1c
.RI "bool \fBno_throw\fP"
.br
.ti -1c
.RI "bool \fBno_exitcode\fP"
.br
.ti -1c
.RI "bool \fBno_run\fP"
.br
.ti -1c
.RI "bool \fBno_intro\fP"
.br
.ti -1c
.RI "bool \fBno_version\fP"
.br
.ti -1c
.RI "bool \fBno_colors\fP"
.br
.ti -1c
.RI "bool \fBforce_colors\fP"
.br
.ti -1c
.RI "bool \fBno_breaks\fP"
.br
.ti -1c
.RI "bool \fBno_skip\fP"
.br
.ti -1c
.RI "bool \fBgnu_file_line\fP"
.br
.ti -1c
.RI "bool \fBno_path_in_filenames\fP"
.br
.ti -1c
.RI "bool \fBno_line_numbers\fP"
.br
.ti -1c
.RI "bool \fBno_debug_output\fP"
.br
.ti -1c
.RI "bool \fBno_skipped_summary\fP"
.br
.ti -1c
.RI "bool \fBno_time_in_output\fP"
.br
.ti -1c
.RI "bool \fBhelp\fP"
.br
.ti -1c
.RI "bool \fBversion\fP"
.br
.ti -1c
.RI "bool \fBcount\fP"
.br
.ti -1c
.RI "bool \fBlist_test_cases\fP"
.br
.ti -1c
.RI "bool \fBlist_test_suites\fP"
.br
.ti -1c
.RI "bool \fBlist_reporters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
OCLINT too many fields\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for math from the source code\&.
