name: doxygen

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Grab repo
      uses: actions/checkout@v4
      with:
        repository: ttaute/math
    
    - name: Generate documentation
      uses: mattnotmitt/doxygen-action@v1

    - name: Move documentation into the correct directory structure
      shell: bash
      run: cd doc && mkdir math && mv html/search ./math && mv html/* ./math && cd ..

    - name: Create artifacts
      uses: actions/upload-artifact@v4
      with:
        path: doc/math
