name: doxygen

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Grab repo
      uses: actions/checkout@v4
      with:
        repository: ttaute/math
    
    - name: Generate documentation
      uses: mattnotmitt/doxygen-action@v1

    - name: Create artifacts
      uses: actions/upload-artifact@v4
      with:
        path: doc/html

    - name: push documentation   
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main' # your branch name goes here
